# Generated by Django 5.0 on 2024-05-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_remove_patientdata_outcome_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
