# Generated by Django 5.0 on 2024-05-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_patientdata_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='cough',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='difficulty_breathing',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='fatigue',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='fever',
            field=models.CharField(max_length=10),
        ),
    ]
