# Generated by Django 5.0 on 2024-05-13 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_patientname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientName',
        ),
    ]
